# Generated by Django 4.1.2 on 2023-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50)),
                ('nome_contato', models.CharField(max_length=50)),
                ('serviço_prestado', models.CharField(blank=True, max_length=300)),
                ('valor', models.FloatField()),
                ('comprovante', models.FileField(default='', upload_to='')),
                ('ano', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50)),
                ('nome_contato', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('valor', models.FloatField(blank=True)),
                ('comprovante', models.FileField(default='', upload_to='')),
                ('ano', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Patrocinador',
            },
        ),
    ]
