# Generated by Django 4.2.2 on 2023-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50)),
                ('nome_contato', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('valor_ct', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Doação')),
                ('comprovante', models.FileField(blank=True, default='', upload_to='')),
                ('ano', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.FloatField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Saidas',
            },
        ),
    ]
