# Generated by Django 4.2.2 on 2023-06-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_congressista_contato'),
        ('balanco_geral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='nome_contato',
        ),
        migrations.AddField(
            model_name='entradas',
            name='nome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.congressista', verbose_name='Congressita'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
