# Generated by Django 4.1.2 on 2023-05-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanco_geral', '0002_parceiros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='valor',
            new_name='valor_ct',
        ),
        migrations.RenameField(
            model_name='parceiros',
            old_name='valor',
            new_name='valor_pc',
        ),
        migrations.RenameField(
            model_name='patrocinador',
            old_name='valor',
            new_name='valor_pt',
        ),
    ]
