# Generated by Django 4.2.2 on 2023-06-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanco_geral', '0002_remove_entradas_nome_contato_entradas_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='nome',
        ),
    ]
