# Generated by Django 4.1.2 on 2023-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco_geral', '0003_rename_valor_contratos_valor_ct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
            ],
        ),
    ]
