# Generated by Django 4.1.2 on 2023-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco_geral', '0004_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='valor_ct',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='valor_pc',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='valor_pt',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
