# Generated by Django 4.1.2 on 2023-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco_geral', '0006_alter_contratos_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='comprovante',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='comprovante',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
