# Generated by Django 4.1.2 on 2023-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanco_geral', '0007_alter_parceiros_comprovante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='valor_total',
            field=models.FloatField(blank=True, editable=False),
        ),
    ]
