# Generated by Django 4.2 on 2023-04-26 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'Lote',
            },
        ),
        migrations.CreateModel(
            name='Congressista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cpf', models.CharField(max_length=11)),
                ('contato', models.IntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=300)),
                ('bairro', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=300)),
                ('uf', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=300)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.categoria')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.lote')),
            ],
            options={
                'verbose_name': 'Congressista',
            },
        ),
    ]
