# Generated by Django 4.2.2 on 2023-06-15 14:36

import apps.user.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Lote',
            },
        ),
        migrations.CreateModel(
            name='Congressista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cpf', models.CharField(max_length=11)),
                ('contato', models.IntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('cep', models.CharField(blank=True, help_text='Digite um CEP válido para atualizar os campos abaixo.', max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('num_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, validators=[apps.user.models.validate_uf], verbose_name='UF')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.categoria')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.lote')),
            ],
            options={
                'verbose_name': 'Congressista',
            },
        ),
    ]
