# Generated by Django 4.1.2 on 2023-05-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='valor',
            new_name='valor_unitario',
        ),
    ]
