# Generated by Django 4.1.2 on 2023-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_valor_lote_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='total_lotes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
