# Generated by Django 4.2.2 on 2023-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_congressista_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressista',
            name='contato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
