# Generated by Django 4.1.2 on 2023-05-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_congressista_total_lotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressista',
            name='total_lotes',
        ),
    ]
