# Generated by Django 4.1.2 on 2023-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_congressista_total_lotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
