# Generated by Django 4.2.2 on 2023-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('CARTAO', 'Cartão de Credito'), ('ESPECIE', 'Espécie'), ('PIX', 'Pix')], default=1, max_length=20, verbose_name='Tipo de Pagamento'),
            preserve_default=False,
        ),
    ]
