# Generated by Django 4.1.2 on 2023-05-11 17:02

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_lote_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='num_endereco',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='congressista',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congressista',
            name='cep',
            field=models.CharField(blank=True, help_text='Digite um CEP válido para atualizar os campos abaixo.', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='congressista',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='congressista',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='congressista',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='congressista',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[apps.user.models.validate_uf], verbose_name='UF'),
        ),
    ]
