# Generated by Django 4.2.2 on 2023-06-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pagamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='numero_da_parcela',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
