# Generated by Django 4.2.2 on 2023-07-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_pagamento_numero_da_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='proxima_parcela',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='numero_da_parcela',
            field=models.IntegerField(),
        ),
    ]
