# Generated by Django 4.2.2 on 2023-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_congressista_proxima_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='numero_parcelass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
