# Generated by Django 4.2.2 on 2023-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_congressista_numero_parcelass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('nome_empresa', models.CharField(max_length=100)),
                ('comprovante', models.ImageField(upload_to='comprovantes/')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('nome_empresa', models.CharField(max_length=100)),
                ('comprovante', models.ImageField(upload_to='comprovantes/')),
            ],
        ),
    ]
