# Generated by Django 4.2.2 on 2023-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_entrada_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='valor_total',
            field=models.FloatField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saida',
            name='valor_total',
            field=models.FloatField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='ano',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='ano',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='saida',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='saida',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
