# Generated by Django 4.2.2 on 2023-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_entrada_valor_total_saida_valor_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='comprovante',
            field=models.ImageField(blank=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='comprovante',
            field=models.ImageField(blank=True, upload_to='comprovantes/'),
        ),
    ]
