# Generated by Django 4.2.2 on 2023-07-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_entrada_valor_total_remove_saida_valor_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congressitas', models.FloatField(default=0.0)),
                ('entradas', models.FloatField(default=0.0)),
                ('saidas', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
    ]
