# Generated by Django 4.2.2 on 2023-07-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='total_parcelas',
            field=models.FloatField(default=0.0),
        ),
    ]
