# Generated by Django 4.2.2 on 2023-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_congressista_total_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='valor_total',
            field=models.FloatField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
