# Generated by Django 4.2.2 on 2023-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_entrada_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='valor_total',
            new_name='valor_total_entrada',
        ),
        migrations.AddField(
            model_name='saida',
            name='valor_total_saida',
            field=models.FloatField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
