# Generated by Django 4.2.2 on 2023-07-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_valor_total_entrada_valor_total_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='congressitas',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='entradas',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='saidas',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='saldo',
        ),
    ]
