# Generated by Django 4.2.2 on 2023-08-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_caixa_congressitas_remove_caixa_entradas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saida',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
