# Generated by Django 4.2.2 on 2023-09-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_entrada_ano_alter_saida_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressista',
            name='contato',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
    ]
