# Generated by Django 4.2.2 on 2023-10-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_congressista_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.categoria'),
            preserve_default=False,
        ),
    ]
