# Generated by Django 4.2.2 on 2023-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_pagamento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='numero_da_parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
