# Generated by Django 4.2.2 on 2023-10-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_congressista_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressista',
            name='categoria',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.categoria'),
        ),
    ]
