# Generated by Django 4.2.2 on 2023-10-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_congressista_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressista',
            name='categoria',
        ),
    ]
