# Generated by Django 4.2.2 on 2024-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_congressista_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressista',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='congressista',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='congressista',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='congressista',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='congressista',
            name='num_endereco',
        ),
        migrations.RemoveField(
            model_name='congressista',
            name='numero_parcelass',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
