# Generated by Django 4.2.2 on 2024-03-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_congressista_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_restante',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='nome_empresa',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saida',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='saida',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
