# Generated by Django 4.2.2 on 2024-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_entrada_nome_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
