# Generated by Django 4.2.2 on 2024-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_congressista_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressista',
            name='passeio_de_barco',
            field=models.BooleanField(default=False),
        ),
    ]
