# Generated by Django 4.2.2 on 2024-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_congressista_passeio_de_barco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressista',
            name='passeio_de_barco',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
    ]
