# Generated by Django 5.0.6 on 2024-09-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_entrada_data_entrada_saida_data_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('valor', models.FloatField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Cadastro Gerais',
                'verbose_name_plural': 'Cadastros Gerais',
            },
        ),
    ]
