# Generated by Django 5.0.6 on 2024-09-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_cadastrogerais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogerais',
            name='valor',
            field=models.FloatField(blank=True),
        ),
        migrations.CreateModel(
            name='Camisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('congressista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.congressista')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camisas_modelo', to='user.cadastrogerais')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camisas_tipo', to='user.cadastrogerais')),
            ],
            options={
                'verbose_name': 'Camisa',
                'verbose_name_plural': 'Camisas',
            },
        ),
    ]
