# Generated by Django 5.0.6 on 2024-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_cadastrogerais_valor_camisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisas',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
