# Generated by Django 5.0.6 on 2024-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_camisas_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisas',
            name='tamanho',
            field=models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
