# Generated by Django 4.2.2 on 2023-08-09 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'mensalidade',
            },
        ),
    ]
