# Generated by Django 4.2.2 on 2023-08-09 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zouk_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='descricao',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
