# Generated by Django 4.2.2 on 2023-08-09 03:26

import apps.zouk_me.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zouk_me', '0002_alter_mensalidade_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('contato', models.IntegerField(blank=True, null=True)),
                ('ano', models.CharField(max_length=4)),
                ('cep', models.CharField(blank=True, help_text='Digite um CEP válido para atualizar os campos abaixo.', max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('num_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, validators=[apps.zouk_me.models.validate_uf], verbose_name='UF')),
                ('proxima_parcela', models.DateField(blank=True, null=True)),
                ('numero_parcelass', models.IntegerField(blank=True, null=True)),
                ('total_parcelas', models.FloatField(default=0.0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zouk_me.categoria')),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zouk_me.mensalidade')),
            ],
            options={
                'verbose_name': 'Aluno',
            },
        ),
    ]
