# Generated by Django 4.2.2 on 2023-08-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zouk_me', '0003_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='num_endereco',
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_da_parcela', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CARTAO', 'Cartão de Credito'), ('ESPECIE', 'Espécie'), ('PIX', 'Pix')], max_length=20, verbose_name='Tipo de Pagamento')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('congressista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zouk_me.aluno')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
